apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-knuth-deployment
spec:
  template:
    spec:
      volumes:
        - name: c-debugging
          hostPath:
            path: /Users/bronifty/codes/temp/c-debugging
            type: Directory
