services:
  ubuntu-with-tailscale:
    build: .
    container_name: ubuntu-with-tailscale-container
    hostname: ubuntu-tailscale
    env_file:
      - .env
    volumes:
      - .:/workspaces/c-debugging
      - tailscale-volume:/var/lib/tailscale
      # - /dev/net/tun:/dev/net/tun
    # privileged: true
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

volumes:
  tailscale-volume:
    driver: local
