apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu22-debug-c-deployment
spec:
  template:
    spec:
      volumes:
        - name: c-debugging
          hostPath:
            path: /absolute/path/to/desired/directory
            type: Directory
