services:
  tailscale-lambda:
    build: .
    container_name: tailscale-lambda-container
    privileged: true # Grants extended privileges; consider using specific capabilities for better security
    environment:
      - TAILSCALE_AUTHKEY=tskey-auth-kEa5droHYa11CNTRL-dqEbCNAaEo22zMd3FGeMi2pL73WLrv2c # Replace with your actual Tailscale auth key
      - TAILSCALE_HOSTNAME=lambda-container # Optional: Set a custom hostname
    ports:
      - "1055:1055" # Expose Tailscale SOCKS5 proxy
    volumes:
      - tailscale-state:/var/lib/tailscale # Named volume for persisting Tailscale state
    restart: unless-stopped

volumes:
  tailscale-state:
