services:
  ubuntu22-debug-c:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu22-debug-c
    # network_mode: host
    stdin_open: true # Keeps STDIN open even if not attached
    tty: true # Allocates a pseudo-TTY
    # Optional: Mount volumes or set environment variables as needed
    volumes:
      - .:/workspaces/c-debugging
    # environment:
    #   - ENV_VAR=value
    # No need to expose ports explicitly with host networking
    # command: /usr/sbin/sshd -D # Starts the SSH daemon
