apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-knuth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-knuth
  template:
    metadata:
      labels:
        app: busy-knuth
    spec:
      containers:
        - name: busy-knuth-container
          image: ghcr.io/bronifty/busy-knuth:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo Container started
              trap "exit 0" 15

              exec "$@"
              while sleep 1 & wait $!; do :; done
            - "-"
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
          volumeMounts:
            - name: c-debugging
              mountPath: /workspaces/c-debugging
            - name: vscode
              mountPath: /vscode
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: c-debugging
          hostPath:
            path: "/absolute/path/to/placeholder"
            type: Directory
        - name: vscode
          persistentVolumeClaim:
            claimName: vscode-pvc
